name: Build paradigm kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [y2q]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 1

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip \
            zstd

      - name: Download prebuilt Google clang
        run: |
          wget -O llvm.tar.zst https://github.com/Ylarod/setup-ndk-clang/releases/download/prebuilt/clang-linux-x86-ndk-r29-r563880c.tar.zst
          mkdir llvm-21
          tar -I unzstd -xf llvm.tar.zst -C llvm-21
          rm llvm.tar.zst

      - name: Build kernel
        run: |
          chmod +x build.sh
          bash build.sh "${{ matrix.device }}"

      - name: Package artifacts
        run: |
          zip -r PrimeKernel-${{ matrix.device }}.zip \
            boot.img \
            dtbo.img \
            out/dtb.img \
            out/arch/arm64/boot/Image

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: PrimeKernel-${{ matrix.device }}
          path: PrimeKernel-${{ matrix.device }}.zip
